# Generated by Django 5.2.8 on 2025-11-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                (
                    "name_ur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Name (Urdu)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class (e.g., 'bi-shop')",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Project Title"),
                ),
                (
                    "title_ur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (Urdu)"
                    ),
                ),
                (
                    "beneficiary_name",
                    models.CharField(max_length=200, verbose_name="Beneficiary Name"),
                ),
                (
                    "beneficiary_phone",
                    models.CharField(max_length=20, verbose_name="Phone"),
                ),
                (
                    "beneficiary_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("beneficiary_address", models.TextField(verbose_name="Address")),
                (
                    "beneficiary_cnic",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="CNIC/ID Number"
                    ),
                ),
                (
                    "family_size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of family members",
                        verbose_name="Family Size",
                    ),
                ),
                ("description", models.TextField(verbose_name="Project Description")),
                (
                    "description_ur",
                    models.TextField(blank=True, verbose_name="Description (Urdu)"),
                ),
                (
                    "business_plan",
                    models.TextField(
                        blank=True,
                        help_text="Detailed business plan and sustainability strategy",
                        verbose_name="Business Plan",
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Requested Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("PKR", "PKR")],
                        default="USD",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Approved Amount",
                    ),
                ),
                (
                    "expected_monthly_recovery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected monthly contribution back to the system",
                        max_digits=10,
                        null=True,
                        verbose_name="Expected Monthly Recovery",
                    ),
                ),
                (
                    "recovery_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Recovery Start Date"
                    ),
                ),
                (
                    "total_recovered",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Recovered Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved - Awaiting Funding"),
                            ("FUNDED", "Funded - In Progress"),
                            ("ESTABLISHED", "Established - Operating"),
                            ("RECOVERING", "Recovering Contributions"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Application Date"
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Approval Date"
                    ),
                ),
                (
                    "funding_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Funding Date"
                    ),
                ),
                (
                    "establishment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Establishment Date"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="Project Image",
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="project_documents/",
                        verbose_name="Supporting Documents",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes from verification team",
                        verbose_name="Verification Notes",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin Notes"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show on homepage",
                        verbose_name="Featured Project",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show on public website",
                        verbose_name="Public Visibility",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.community",
                        verbose_name="Community",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.projectcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Update Title"),
                ),
                (
                    "title_ur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (Urdu)"
                    ),
                ),
                ("content", models.TextField(verbose_name="Update Content")),
                (
                    "content_ur",
                    models.TextField(blank=True, verbose_name="Content (Urdu)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="project_updates/",
                        verbose_name="Update Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Update",
                "verbose_name_plural": "Project Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Recovery Amount"
                    ),
                ),
                ("recovery_date", models.DateField(verbose_name="Recovery Date")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("MOBILE", "Mobile Payment"),
                        ],
                        default="CASH",
                        max_length=10,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference Number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recoveries",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recovery",
                "verbose_name_plural": "Recoveries",
                "ordering": ["-recovery_date"],
            },
        ),
    ]
