# Generated by Django 5.2.8 on 2025-11-13 00:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "title_ur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Title (Urdu)"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("content", ckeditor.fields.RichTextField(verbose_name="Content")),
                (
                    "content_ur",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Content (Urdu)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=False,
                        help_text="Display link in footer menu",
                        verbose_name="Show in Footer",
                    ),
                ),
                (
                    "show_in_header",
                    models.BooleanField(
                        default=False,
                        help_text="Display link in header menu",
                        verbose_name="Show in Header",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["title"],
            },
        ),
    ]
