# Generated by Django 5.2.8 on 2025-11-13 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("PKR", "Pakistani Rupee"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="USD",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Transfer"),
                            ("CASH", "Cash"),
                            ("CARD", "Credit/Debit Card"),
                            ("MOBILE", "Mobile Payment"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK",
                        max_length=10,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Reference/Transaction Number",
                    ),
                ),
                ("date_received", models.DateField(verbose_name="Date Received")),
                (
                    "receipt_issued",
                    models.BooleanField(default=False, verbose_name="Receipt Issued"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations",
                        to="core.donor",
                        verbose_name="Donor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "ordering": ["-date_received", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount from this donation allocated to this project",
                        max_digits=12,
                        verbose_name="Allocated Amount",
                    ),
                ),
                (
                    "allocated_date",
                    models.DateField(auto_now_add=True, verbose_name="Allocation Date"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Allocation Notes"),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="donations.donation",
                        verbose_name="Donation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation Allocation",
                "verbose_name_plural": "Donation Allocations",
                "ordering": ["-allocated_date"],
                "unique_together": {("donation", "project")},
            },
        ),
    ]
